- about.html
Description
This PR addresses Issue #16  (text alignment on the About Us page).
I updated the text alignment from center to justify for the About Us content to improve readability, especially for longer paragraphs on larger screens.
Motivation & Context
Improved Readability: Justified text makes it easier to scan and follow, reducing visual strain.
Professional Aesthetic: It brings an editorial, premium look to the layout.
Responsive Elegance: Looks cleaner and more structured on desktop and tablet views.
This small UI enhancement adds polish and boosts trust in our platform — showing we care about the finer details.
Fixes: #16 
Contributor: Tanush Gupta
BEFORE:
AFTER:
> Improve Readability of About Subpage by Justifying Text #16

- about.html
- contact.html
- index.html
- service.html
Description:
This PR adds a favicon to the browser tab for better branding and user experience. The favicon is now visible when the website is opened in the browser.
Changes made:
Added logo_blue.png file to the project directory
Linked the favicon in the <head> section of index.html using
Issue #9 
Contributed as a part of GSSoC'25.
Thankyou
> Add favicon logo to the website

- index.html
Reverts sachiva1/sachiva#45
Hi @Soumyosish,
Thanks for the fix — the unnecessary word and gap are resolved. However, I noticed the change unintentionally affected the dark mode behavior. I'll need to revert this PR to prevent further UI issues.
Feel free to open a new PR with the necessary fixes while ensuring dark mode compatibility is retained. Let me know if you need any clarification!
> Revert "Fixed the Bug"

- index.html
- js/custom.js
This PR adds the "Help Me Choose" feature to the homepage. It includes:
- A recommendation section based on user-selected category (Business, Design, etc.)
- Dynamic rendering of cards with service options
- Integrated smooth toggle for dark/light theme
- Scroll-to-top functionality
Checklist
-  Feature works as expected
- Dark mode supported
- No major styling or JS issues
- Only intended files (`index.html`, `custom.js`) were modified
- Fixes #88
> Add Help Me Choose Feature to Home Page

- css/style.css
- index.html
Issue #87 
Modified the client section 
Added transition effect to client box and sliding arrows
Given some box shadow on hovering to make it look good
Added linear gradient to the box and arrows 
Made heading bold and changed the color as heading needs to look different from paragraph .
Have kept in mind about dark mode and added color as it will work on it.
> Modified Client Section

- contributors.html
- css/style.css
- js/service.js
- service.html
This pull request introduces a new filter feature and UI enhancements:
✨ Services Section:
- Implemented dynamic filter buttons to display service cards based on selected category.
- Ensured smooth interactivity with proper show/hide logic using JavaScript.
- Improved layout and spacing for better visual clarity.
🎯 Heading Spacing Fixes:
- "Our Services"
- "Reliable IT Solutions" (Hero section)
- "Our Contributors"
→ Adjusted padding to ensure headings are no longer cut off and are properly aligned.
These changes enhance both the **usability** and **visual consistency** of the page.
Looking forward to feedback or suggestions!
https://github.com/user-attachments/assets/7e970614-7dcd-4fa3-bd5c-75b957f6c71a
>  Added Filter Functionality & Fixed UI Alignment in Services and Other Sections

- about.html
- css/style.css
Issue #100 
@sumitrathor1 Solved the conflicts now you can merge it to main branch.
After look
https://github.com/user-attachments/assets/2308b1db-2cce-48ef-b92d-a45ed3f56798
> Updated About page

- .github/WORKFLOWS/issue-create-automate-message.yml
I have added the automate message on issue created to enhance the user for better enhancement of the project.
Fixes #128 
Please @sumitrathor1 check and merge the PR and add the gssoc25 label and the level of contribution. Let me know if require any changes
> automate message in issue create added

- html/portfolio.html
Issue #125 
Changes Made -
Added animation in hearo section 
Added google font for heading of hearo section 
Changed the font styles
Added box shadow to give hero section little 3d look 
Added linear gradient to portfolio section heading 
And added blue glassy background to paragraph of portfolio section to give neat look
Have kept in mind about dark background and added style according to it.
After
https://github.com/user-attachments/assets/c264f75f-beb9-48eb-90e2-ad22e9fadb76
> Portfolio Page Style Change

- css/dark-mode-fixes.css
- css/style.css
- index.html
Hi @sumitrathor1,
📌 Description:
Improved the visual appearance and interactivity of the buttons under the "Not Sure What You Need?" section by:
Adding consistent spacing between buttons.
Applying smooth hover transitions (scale + shadow).
Ensuring compatibility with both light and dark modes.
🧪 How to Test
Hover over the buttons: they now scale up slightly and cast a shadow.
Works in both light and dark themes.
Responsive on various screen sizes.
Closes #140
> Enhanced UI for smart recommender buttons with spacing and hover effect( #140)

- css/style.css
- html/blog.html
Issue #162 
Added gradients to cards in bright and dark mode both 
Added padding 
Solved bug occurring in mobile devices, container was not given proper margin
Added animation to button and enhanced the border to make it look good.
After
https://github.com/user-attachments/assets/334fe4c1-8606-4257-8c08-5f3a452e89ee
> Blog Style Change

- .github/WORKFLOWS/issue-create-automate-message.yml
I have corrected bug in issue create automate message.
fixes #175 
Please @sumitrathor1 check and merge the PR also add the  gssoc25 label and the level of contribution. Let me know if require any  changes.
I will create a dummy issue to test whether the  github actions bot is working or not as soon as the pr gets merged.
> corrected bug in issue create automate message

- html/booking-confirmation.html
- html/booking.html
🎯 Overview
This PR introduces a fully-featured booking confirmation page that provides users with a professional and comprehensive confirmation experience after completing their service booking.
✨ Key Features Added-
🎨 Modern UI/UX Design
-Glassmorphism Design: Implemented a modern glassmorphism effect with backdrop blur and transparency
-Responsive Layout: Fully responsive design that works seamlessly across all device sizes
-Interactive Elements: Hover effects, smooth transitions, and visual feedback
-Professional Styling: Clean, modern interface with consistent branding
📋 Comprehensive Booking Summary
Dynamic Data Display: Shows all booking details including:
-Unique booking ID with gradient styling
-Customer information (name, email, phone, location)
-Service details with emoji icons …
> Feature: Added Booking Confirmation Page with Summary

- html/booking-confirmation.html
- html/booking.html
- html/service.html
Updated the service pricing structure across all service cards and enhanced the visual styling of flip cards for better user experience.
Changes Made
Service Pricing Updates-
- **Home Maintenance**: Updated to ₹150–₹300 per hour (Base Rate) / ₹500–₹900 per day (Full Service)
- **Cleaning Services**: Updated to ₹400–₹800 (1BHK) / ₹1,500–₹3,000 (2BHK+)
- **Renovation & Painting**: Updated to ₹10–₹15 per sq. ft. (Labour) / ₹2,000–₹4,000 per room
- **Appliance Repair**: Updated to ₹150–₹300 (Inspection Fee) / ₹300–₹1,000 (Repair + Parts)
- **Security Systems**: Updated to ₹400–₹800 per camera / ₹1,500–₹3,000 (Full Home Setup)
- **Pest Control**: Updated to ₹500–₹1,200 (2BHK) / ₹1,500–₹2,500 (Big House/Full Package)
- **Gardening & Landscaping**: Updated to ₹300–₹700 per visit (Maintenance) / …
> Update service, enhance flip cards with rate on them

- css/style.css
- html/service.html
- index.html
#234 
Description:
This PR introduces a newsletter subscription form in the footer to improve user engagement. Users can now subscribe using their email, and receive immediate feedback via toast notifications.
Changes Made:
Added newsletter input field + Subscribe button in the footer.
Implemented email validation (checks for proper format).
Integrated toast notifications for user feedback:
✅ Success → “You have successfully subscribed!”
❌ Error → “Please enter a valid email.”
Positioned the newsletter section above contact and social links.
Applied minimal UI design (white input box + green/blue button).
Toasts appear in the bottom-right for better visibility.
Preview:
Users can now easily subscribe via the footer.
Invalid emails are rejected with an error toast.
Valid subscriptions …
> Add Newsletter Subscription with Toast Notifications

- html/booking.html
Issue id : #207 
This pull request resolves the issue of manual location and date entry on the "Book a Service" form. It introduces a location autocomplete feature and enhances the date picker to improve user experience, reduce typing errors, and speed up the form-filling process.
The implementation uses the Google Places API to provide real-time, accurate address suggestions as the user types.
> Added location suggestion and improved date picker

- html/service.html
I have enhanced the faqs section with the feature of + - to make the user easily understand the faqs and increase the efficiency of the website.
Please @sumitrathor1 check and merge the PR and add the gssoc25 label along with the level of contribution .Let me know if require any changes.
fixes #229
> enhanced the faqs section

- html/service.html
- index.html
I have enhanced the style of the buttons 
Please @sumitrathor1 check and merge the PR and add the gssoc25 label along with the level of contribution. Let me know if require any changes.
fixes #232
> Enhancement of buttons

- README.md
corrected the alt text to make the image properly visible instead of the link in the readme.md. Please @sumitrathor1 check and merge the pr and  add the gssoc25 label along with the level of contribution. Let me know if require any changes.
fixes #250
> Readme link update

- html/about.html
- html/blog.html
- html/booking-confirmation.html
- html/contact.html
- html/contributors.html
- html/feedback.html
- html/forum.html
- html/portfolio.html
- html/service.html
- index.html
**Closes #263**
**Description:**
This pull request implements the requested feature to add AOS (Animate On Scroll) animations to the Sachiva website. The goal is to enhance user experience by adding smooth and modern fade, slide, and zoom effects as content sections come into view.
**Changes Implemented:**
- Integrated the AOS library via CDN links into `index.html`, `about.html`, `service.html`, `contact.html`, `forum.html`, `blog.html`, `contributors.html`, and `portfolio.html`.
- Initialized the AOS library with `AOS.init()` in all affected HTML files.
- Applied `data-aos` attributes to key sections and elements across the website to trigger animations on scroll.
- Used various animation effects such as `fade-up`, `fade-right`, `fade-left`, and `zoom-in` with staggered delays to create …
> feat: add AOS animations for better UI/UX
